services:
  quepid-api-app:
    container_name: quepid-api-app
    image: frutik777/quepid-api-unofficial
    build:
      context: ./quepid_api
      dockerfile: ../Dockerfile
      target: app
    env_file:
      - .env
    environment:
      DEBUG: 1
    network_mode: service:quepid-api-web
  quepid-api-web:
    container_name: quepid-api-web
    image: frutik777/quepid-api-unofficial-web
    build:
      context: ./quepid_api
      dockerfile: ../Dockerfile
      target: web
    ports:
      - '8081:80'
