apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quepid_chart.name" . }}
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    {{- include "quepid_chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.kubernetes.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "quepid_chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "quepid_chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "quepid_chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.appVersion | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.appVersion | default .Chart.AppVersion }}"
            - name: UWSGI_SOCKET
              value: "127.0.0.1:8001"
            - name: UWSGI_MASTER
              value: "1"
            - name: UWSGI_STATS
              value: "127.0.0.1:9191"
            - name: UWSGI_WSGI_FILE
              value: "quepid_api/wsgi.py"
            - name: UWSGI_CHDIR
              value: "/app/"
            - name: UWSGI_THREADS
              value: "20"
            - name: UWSGI_CHEAPER_ALGO
              value: "spare"
            - name: UWSGI_CHEAPER
              value: "2"
            - name: UWSGI_CHEAPER_INITIAL
              value: "5"
            - name: UWSGI_WORKERS
              value: "1000"
            - name: UWSGI_CHEAPER_STEP
              value: "2"
            - name: DJANGO_DEBUG
              value: "{{ .Values.django.debug }}"
            - name: DJANGO_SECRET
              value: "{{ .Values.django.secret }}"
            - name: QUEPID_DB_NAME
              value: "{{ .Values.quepid.db.name }}"
            - name: QUEPID_DB_USER
              value: "{{ .Values.quepid.db.user }}"
            - name: QUEPID_DB_PASSSWORD
              value: "{{ .Values.quepid.db.password }}"
            - name: QUEPID_DB_HOST
              value: "{{ .Values.quepid.db.host }}"
            - name: QUEPID_DB_PORT
              value: "{{ .Values.quepid.db.port }}"
