---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quepid_chart.name" . }}
  namespace: {{ .Values.kubernetes.namespace }}
  labels:
    {{- include "quepid_chart.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.uwsgi.socket_port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "quepid_chart.name" . }}
