name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with "v" (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build --target app -f ../Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/quepid-api-unofficial:${{ github.ref_name }} ./quepid_api

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/quepid-api-unofficial:${{ github.ref_name }}

      - name: Build Docker image 2
        run: |
          docker build --target web -t ${{ secrets.DOCKER_USERNAME }}/quepid-api-unofficial-web:${{ github.ref_name }} ./quepid_api

      - name: Push Docker image to Docker Hub 2
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/quepid-api-unofficial-web:${{ github.ref_name }}
